Added new stack with one slice using new lazy loading functionality
juiceinc/implementation-jb3demo pull request #1
Opened 2018-10-24 22:33 UTC by LauraBuzek

2018-10-24 22:34 UTC, LauraBuzek commented
@03stories Added the new lazy loading functionality to core, added an extra stack to jb3demo using the new loading technique, reflected in the use of build_recipe inside censusv2service.py

2018-10-25 15:22 UTC, LauraBuzek commented
https://dev.juiceboxdata.com/jb3demo/census2lazyloads

2018-10-25 17:04 UTC, 03stories commented
@LauraBuzek Hmmm. I tried the test, but it seems like that 1st slice isn't actually loading on _either_ stack. Try taking a look.

2018-10-25 23:26 UTC, LauraBuzek commented
@03stories If you can take another quick look tomorrow morning, this should be in tact now. Turns out we hadn't updated dev to have the new changes on it!

2018-10-26 15:18 UTC, radix requested changes
I think you can delete templates.html.

2018-10-26 15:18 UTC, radix commented on stacks/census2lazyloads/templates.html
> +Templates allow you to change how html is rendered into a juicebox stack. See the templates guide for more details.
I think you can delete this template.html file, because there are no slices in this stack that use any of the templates defined in it.

2018-10-26 15:23 UTC, radix approved these changes
LGTM

2018-10-26 15:45 UTC, merged